# Generated by Django 5.1 on 2024-09-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0020_appointment_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passward',
            new_name='password',
        ),
    ]
