# Generated by Django 5.1 on 2024-09-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0022_rename_categorie_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='passward',
            new_name='password',
        ),
    ]
