# Generated by Django 4.2.16 on 2024-09-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="image",
            field=models.ImageField(null=True, upload_to="cars/"),
        ),
    ]
