# Generated by Django 4.2.16 on 2024-09-14 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_carmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="drive_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="engine",
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="ground_clearance",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="power",
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="review",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=1,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="seating_capacity",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="torque",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dealer",
            name="image",
            field=models.ImageField(null=True, upload_to="dealers/"),
        ),
    ]
