# Generated by Django 4.2.16 on 2024-09-14 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0003_carmodel_description_carmodel_drive_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="car",
            field=models.ManyToManyField(related_name="car", to="car.carmodel"),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="review",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
