# Generated by Django 5.1.1 on 2024-09-22 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_dealer_car_alter_carmodel_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('upcomingyear', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='cars/')),
                ('engine', models.CharField(max_length=225, null=True)),
                ('power', models.CharField(max_length=225, null=True)),
                ('seating_capacity', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('drive_type', models.CharField(max_length=255, null=True)),
                ('ground_clearance', models.CharField(max_length=255, null=True)),
                ('torque', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
